# Generated by Django 4.2.7 on 2024-01-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
